function response = sel_clust_popup(handles)
    scrsz = get(groot, 'ScreenSize');
    fig_height = 50 + 30 * handles.curr_container.n_clusters;
    fig_width = 150;
    fig_position = [scrsz(3)/2, scrsz(4)/2, fig_width, fig_height];
    f = figure('Position', fig_position);
    colors = lines(handles.curr_container.n_clusters);
    buttons = cell(handles.curr_container.n_clusters, 1);
    for i = 1:handles.curr_container.n_clusters
        position = [0, 50 + 30*(i-1), 160, 30];
        buttons{i} = uicontrol(f, ...
            'Style', 'checkbox', ...
            'String', num2str(i), ...
            'Value', ~handles.curr_container.valid_class(i), ...
            'BackgroundColor', colors(i, :), ...
            'Position', position ...
        );
        exit_button = uicontrol(f, ...
            'Style', 'togglebutton', ...
            'Value', false, ...
            'Position', [0, 20, 160, 20], ...
            'String', 'Exit' ...
        );
    end

    while ~exit_button.Value
        pause(1)
    end

    response = zeros(size(buttons));
    for i = 1:length(response)
        response(i) = buttons{i}.Value;
    end
    close(f)