function dt = spike_time_to_datetime(fst, spike_start)
%% dt = spike_time_to_datetime(file_start_time, spike_start)
%
% file_start_time is an Axion DateTime struct. To compute the correct spike time, this should be read from
%  Spike.Source.Header.FileStartTime
%   or
%  AxisFile.DataSets.Header.FileStartTime
%
%  spike_start is the time of the spike with respect to the start of the recording, in seconds. This can
%   be found at
%  Spike.Start
    if ~exist('spike_start', 'var')
        spike_start = 0;
        dt = datetime( ...
            fst.Year, ...
            fst.Month, ...
            fst.Day, ...
            fst.Hour, ...
            fst.Minute, ...
            fst.Second + spike_start, ...
            fst.Millisecond...
            );
    else
        dt = datetime( ...
            fst.Year, ...
            fst.Month, ...
            fst.Day, ...
            fst.Hour, ...
            fst.Minute, ...
            fst.Second + spike_start ...
            );
    end
